{{- if and (not .Values.dockerHubCredentials.existingSecret) (and .Values.dockerHubCredentials.username .Values.dockerHubCredentials.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dockerhub-ratelimit-exporter.fullname" . }}
  labels:
    {{- include "dockerhub-ratelimit-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  DOCKER_HUB_USERNAME: {{ .Values.dockerHubCredentials.username | b64enc }}
  DOCKER_HUB_PASSWORD: {{ .Values.dockerHubCredentials.password | b64enc }}
{{- end }}