{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dockerhub-ratelimit-exporter.fullname" . }}
  labels:
    {{- include "dockerhub-ratelimit-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - port: http
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      honorLabels: true
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
      {{ toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "dockerhub-ratelimit-exporter.selectorLabels" . | nindent 6 }}
{{- end }}