name: Build Docker image and push it to Docker Hub

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/build-image.yaml
      - Containerfile
      - app.py
      - requirements.txt
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Retrieve desired release version
        run: |
          git config --global --add safe.directory '*'
          git describe --exact-match --tags HEAD > /dev/null 2>&1 && \
          echo "app_version_oci=$(git describe --exact-match --tags HEAD)" >> "$GITHUB_ENV" || \
          echo "app_version_oci=0.0.0-test_$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha,format=long

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Containerfile
          push: true
          sbom: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ env.app_version_oci }},${{ env.IMAGE_NAME }}:latest

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Attest
        uses: actions/attest-build-provenance@v2.1.0
        id: attest
        with:
          subject-name: index.docker.io/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
